(*
Nama         : Vini Arifiani Rohmat
NPM          : 20.14.1.0003
Nama Program : TUGAS1-1.pas
*)

program biodata;
uses crt;

begin
clrscr;
writeln('------------------------------');
writeln('BIODATA');
writeln('Nama   : Vini Arifiani Rohmat');
writeln('NPM    : 20.14.1.0003');
writeln('Alamat : Majalengka');
writeln('TTL    : Majalengka, 16 September 2002');
writeln('No.HP  : 08522322XXXX');
writeln('Motto  : Belajar dari kesalahan untuk memperbaiki diri menjadi lebih baik');
writeln('------------------------------');
readln;

end.